### ISSUE TITLE
Update 1.16.1 -> 1.16.1 fails

### ISSUE THREAD

**Issue by mebster** [nuvlabox/nuvlabox#25]
Error from Nuvla.io job (https://nuvla.io/ui/api/job/8884d24e-dfc2-4f6b-9ac5-43ecfa322e60):

[NuvlaBox Engine update to 1.16.1] update ERROR: unknown option --current-environment
,VERSION

 -- NuvlaBox Engine installer -- 

Usage: ./installer [COMMAND] [ARGS]

 -h --help				Show this help information

COMMANDS:
 install				Install the NuvlaBox Engine
 update					Update an existing NuvlaBox Engine installation
 uninstall				Shutdown (and optionally delete) an existing NuvlaBox Engine installation

INSTALL args:
 --compose-files=<list>			(optional) Comma-separated list of compose files to deploy. If not passed, it uses all
 --environment=<list>			(optional) Comma-separated list of ENV=VALUE keypairs
 --target-version=<string>		(optional) NuvlaBox Engine release to be installed. If not passed, it uses the master branch
 --project=<string>			(optional) Project name used during the first installation. Default is 'nuvlabox'
 --quiet				(optional) Only print final status message

UDPATE args:
 --compose-files=<list>			Comma-separated list of compose files to deploy
 --current-environment=<list>		(optional) Comma-separated list of current ENV=VALUE keypairs, in case a rollback is needed
 --new-environment=<list>		(optional) Comma-separated list of new ENV=VALUE keypairs
 --on-update-failure=<string>		Action be take in case the update fails ('rollback' 'ignore' 'retry'). Default: rollback
 --project=<string>			Project name used during the first installation
 --quiet				(optional) Only print final status message
 --target-version=<string>		NuvlaBox Engine version to be installed. Must match a release from https://github.com/nuvlabox/deployment/releases
 --working-dir=<string>			Directory, on the host, from where the NuvlaBox Engine was installed the first time, and where the corresponding config files can be found

UNINSTALL args:
 --project=<string>			(optional) Project name used during the first installation. Default is 'nuvlabox'
 --quiet				(optional) Only print final status message

**Comment by cjdcordeiro** [comment]
escaping problem. Fix submitted, to be tested

**Comment by cjdcordeiro** [comment]
https://github.com/nuvla/job-engine/pull/169

**Comment by cjdcordeiro** [comment]
tested and working
